import { useState, useEffect } from 'react';
import { 
  Box, 
  Typography, 
  Container, 
  Grid, 
  Card, 
  CardContent,
  CardMedia,
  Chip,
  Alert,
  CircularProgress
} from '@mui/material';

/**
 * SVG Verification Page
 * 
 * Displays all pre-generated SVG muscle diagrams for visual verification.
 * Shows the exercise name, primary/secondary muscles, and the SVG image.
 */
function SVGVerification() {
  const [manifest, setManifest] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    // Load the manifest file
    const baseUrl = import.meta.env.BASE_URL || '/';
    fetch(`${baseUrl}svg-muscles/manifest.json`)
      .then(response => {
        if (!response.ok) {
          throw new Error('Failed to load manifest');
        }
        return response.json();
      })
      .then(data => {
        setManifest(data);
        setLoading(false);
      })
      .catch(err => {
        setError(err.message);
        setLoading(false);
      });
  }, []);

  const baseUrl = import.meta.env.BASE_URL || '/';

  if (loading) {
    return (
      <Container sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh' }}>
        <CircularProgress />
      </Container>
    );
  }

  if (error) {
    return (
      <Container sx={{ py: 4 }}>
        <Alert severity="error">Error loading SVGs: {error}</Alert>
      </Container>
    );
  }

  return (
    <Container maxWidth="xl" sx={{ py: 4 }}>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h3" component="h1" gutterBottom>
          SVG Muscle Diagrams - Visual Verification
        </Typography>
        <Typography variant="body1" color="text.secondary" gutterBottom>
          Pre-generated static SVG muscle diagrams for exercises without demo webp images.
        </Typography>
        <Alert severity="info" sx={{ mt: 2 }}>
          Total SVGs: {manifest.length} | 
          Location: /public/svg-muscles/ | 
          Generated by: scripts/generate-muscle-svgs.js
        </Alert>
      </Box>

      <Grid container spacing={3}>
        {manifest.map((item, index) => (
          <Grid item xs={12} sm={6} md={4} lg={3} key={index}>
            <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
              <CardMedia
                component="img"
                height="200"
                image={`${baseUrl}svg-muscles/${item.filename}`}
                alt={item.exerciseName}
                sx={{ 
                  objectFit: 'contain', 
                  bgcolor: 'background.default',
                  p: 2
                }}
                onError={(e) => {
                  e.target.style.display = 'none';
                  e.target.nextSibling.style.display = 'flex';
                }}
              />
              <Box 
                sx={{ 
                  display: 'none', 
                  height: 200, 
                  alignItems: 'center', 
                  justifyContent: 'center',
                  bgcolor: 'error.light',
                  color: 'error.contrastText'
                }}
              >
                Failed to load
              </Box>
              <CardContent sx={{ flexGrow: 1 }}>
                <Typography variant="h6" component="h2" gutterBottom sx={{ fontSize: '1rem' }}>
                  {item.exerciseName}
                </Typography>
                <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5, mb: 1 }}>
                  <Chip 
                    label={item.primaryMuscle} 
                    size="small" 
                    color="error"
                    sx={{ fontSize: '0.7rem' }}
                  />
                  {item.secondaryMuscles && (
                    <Chip 
                      label={item.secondaryMuscles} 
                      size="small" 
                      color="secondary"
                      sx={{ fontSize: '0.7rem' }}
                    />
                  )}
                </Box>
                <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
                  {item.filename}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Container>
  );
}

export default SVGVerification;
